### ISSUE TITLE
Visually appealing and descriptive 

### ISSUE THREAD

**Issue by IainJackson90** [IainJackson90/pp4-holiday-dreams#1]
As a **visitor** I can **view the site** so that **I can get a feel for the user experience**

### Acceptance Criteria

- Create a descriptive Landing page 
- Easy to navigate through the web pages
- Create a familiar feel to each page so the user knows what is expected on the page

### Tasks

- [x] With the use of images and visually appealing colors to give you a UX of what to expect from the website
- [x] Have descriptive navigation tags and visually display on which page you are on
- [x] Have a well planned theme and layout for each page that would give the user a idea of what page they are on
