### ISSUE TITLE
 Manage post

### ISSUE THREAD

**Issue by IainJackson90** [IainJackson90/pp4-holiday-dreams#3]
As a **User** I can **create and manage post** so that **I can share posts**

### Acceptance Criteria

- User can create posts
- User can edit their post
- User can delete their post

### Tasks

- [ ]Create a model for the user to add their own post ( Title, Slug, Image, Content )
- [x] Create full CRUD Functionality for the user post
- [x] Give a visual notification that post was successful
