### ISSUE TITLE
Manage comments

### ISSUE THREAD

**Issue by IainJackson90** [IainJackson90/pp4-holiday-dreams#4]
As a **User** I can **comment** so that **I can leave feedback on another user post**

### Acceptance Criteria

- User can create and leave comments on another user post
- Have a display of how many comets are in a post

### Tasks

- [x] Give the user full CRUD functionality of the comments thy create
- [x] Create a display counter of all the comments in a post
- [x] Give a visual notification that comment was successful
